### ISSUE TITLE
Restart-Dashing script does not work ubuntu

### ISSUE THREAD

**Issue by fwehuerguweioergjioerier** [mocdaniel/dashing-icinga2#126]
Hey, I want dashing to start automatically with system boot.
The script "restart-dashing" shows error at Line 78, 79, 90.
Could you please help me? What do I need to change in the script for it to work?

Execute script -> `sudo ./restart-dashing`

Output:
```
./restart-dashing: line 78: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
./restart-dashing: line 79: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
./restart-dashing: line 90: dashing: command not found
Restart failed. Bailing out.
```

* Ruby version (`ruby -V`): ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
* Version of this project (tarball name, tag name or `git show -1`): latest
* Operating System and version: Ubuntu 20.04.4 LTS

**Comment by mocdaniel** [comment]
Hi,

the first two logs are due to your OS not having set a valid locale, see [this page on Ubuntu Help](https://help.ubuntu.com/community/Locale).

The last logged message is probably shown because whatever you use to execute `./restart-dashing` does not know how/where to find the `dashing` gem.

I'd suggest you use the provided `dashing-icinga2.service` file to run dashing-icinga2 as a daemon as [described in the README.md](https://github.com/mocdaniel/dashing-icinga2#systemd-service), this seems to cover your use-case best.

**Comment by fwehuerguweioergjioerier** [comment]
Welp, didn't work for me, but I'm a linux noob, so maybe I'm just doing it wrong.
(I use ubuntu and the readme is only for Redhat/CentOS/Debian (?))

I took a workaround and made a script with the `systemctl start dashing-icinga2.service` command and created a crontab.

Thanks for the fast reaction!
